matrix:
  include:
    - language: node_js
      node_js:
        - '10'
      cache:
        directories:
          - web/node_modules
      before_install:
        - cd web/
      install:
        - npm install
      script:
        - npm run lint
        - npm run test:coverage
        - npm run build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: go
      dist: xenial
      go:
        - 1.12.x
      env:
        - GO111MODULE=on
      install: true
      script:
        - make check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
